name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          check-latest: true

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Packages
        run: pnpm build

      - name: Lint and Format
        run: pnpm lint && pnpm format:check

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version:release
          publish: pnpm ci:publish:release
        env:
          GITHUB_TOKEN: ${{ github.token }}
