name: Test

on:
  pull_request:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          check-latest: true

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Packages
        run: pnpm build

      - name: Lint and Format
        run: pnpm format:check && pnpm lint

      - name: Run Tests
        run: pnpm test
